[package]
name = "portfolio"
version = "0.1.0"
authors = ["lima1909"]
edition = "2018"

[dependencies]
log = "0.4.8"
simplelog = "0.7.4"

chrono = "0.4.11"
serde = { version = "1.0.105", features = ["derive"] }
jsonwebtoken = "7.1.0"